# Generated by Django 5.2.4 on 2025-07-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0002_processingtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='assay_ag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='assay_cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='assay_file',
            field=models.FileField(blank=True, null=True, upload_to='assay_files/'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='assay_pb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='assay_zn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='china_import_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='free_of_harmful_impurities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='inland_freight_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='refining_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='shipment_period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='shipment_period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='shipments_evenly_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='treatment_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.deliverypoint'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='delivery_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.deliveryterm'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.packaging'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='transport_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.transportmode'),
        ),
    ]
