# Generated by Django 5.2.4 on 2025-07-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0003_deliverypoint_deliveryterm_packaging_transportmode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('contact_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggeringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='cost_sharing_buyer',
            field=models.IntegerField(default=50, help_text='Cost sharing percentage for buyer (0-100)'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='cost_sharing_seller',
            field=models.IntegerField(default=50, help_text='Cost sharing percentage for seller (0-100)'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='final_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='final_payment',
            field=models.TextField(blank=True, help_text='Final payment terms'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='payment_clause',
            field=models.TextField(blank=True, default='Payment shall be made within 30 days of invoice date'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='prepayment_percentage',
            field=models.IntegerField(default=0, help_text='Prepayment percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='provisional_payment',
            field=models.TextField(blank=True, help_text='Provisional payment terms'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='surveyor_clause',
            field=models.TextField(blank=True, default='Surveyor shall be mutually agreed upon by both parties'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='wsmd_clause',
            field=models.TextField(blank=True, default='Weighing, sampling, moisture determination and analysis shall be carried out at final destination'),
        ),
        migrations.AlterField(
            model_name='businessconfirmation',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.buyer'),
        ),
        migrations.AlterField(
            model_name='businessconfirmation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.material'),
        ),
        migrations.AlterField(
            model_name='businessconfirmation',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessconfirmation',
            name='quantity_tolerance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='businessconfirmation',
            name='seller',
            field=models.CharField(default='Open Mineral Ltd', max_length=100),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.currency'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.paymentmethod'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='nominated_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.surveyor'),
        ),
        migrations.AddField(
            model_name='businessconfirmation',
            name='triggering_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confirmation.triggeringevent'),
        ),
    ]
